# Generated by Django 4.0.6 on 2022-07-17 14:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente', models.BooleanField()),
                ('tipoIdentificacion', models.CharField(choices=[('1', 'RUC'), ('2', 'CEDULA'), ('3', 'PASAPORTE'), ('4', 'ID DEL EXTERIOR')], default=2, max_length=2)),
                ('identificacion', models.CharField(max_length=10, unique=True)),
                ('identificacionIESS', models.CharField(max_length=10)),
                ('fechaNacimiento', models.DateField()),
                ('primerNombre', models.CharField(max_length=50)),
                ('segundoNombre', models.CharField(max_length=50)),
                ('primerApellido', models.CharField(max_length=50)),
                ('segundoApellido', models.CharField(max_length=50)),
                ('nivelInstruccion', models.CharField(choices=[('1', 'PRIMARIA'), ('2', 'SECUNDARIA'), ('3', 'TECER NIVEL'), ('4', 'CUARTO NIVEL'), ('5', 'PHD')], max_length=20)),
                ('genero', models.CharField(choices=[('1', 'FEMENINO'), ('2', 'MASCULINO')], max_length=10)),
                ('estadoCivil', models.CharField(choices=[('1', 'SOLTERO'), ('2', 'CASADO'), ('2', 'DIVORCIADO'), ('2', 'VIUDO'), ('2', 'UNION DE HECHO')], max_length=20)),
                ('fechaInicio', models.DateField(auto_now_add=True)),
                ('tipoContrato', models.CharField(choices=[('1', 'Indefinido'), ('2', 'Obra Cierta'), ('3', 'Jornada Parcial Permanente'), ('4', 'Eventual Continuo'), ('5', 'Eventual Discontinuo'), ('6', 'De Temporada'), ('7', 'De Aprendizaje')], max_length=20)),
                ('tipoSalario', models.CharField(choices=[('1', 'CON SALARIO NETO'), ('2', 'SIN SALARIO NETO')], max_length=20)),
                ('salarioNominal', models.FloatField()),
                ('cargo', models.CharField(max_length=150)),
                ('acumulacionXIII', models.CharField(choices=[('1', 'NO ACUMULA'), ('2', 'EMPRESA'), ('3', 'IESS')], max_length=20)),
                ('acumulacionXIV', models.CharField(choices=[('1', 'NO ACUMULA'), ('2', 'EMPRESA'), ('3', 'IESS')], max_length=20)),
                ('acumulacionFR', models.CharField(choices=[('1', 'NO ACUMULA'), ('2', 'EMPRESA'), ('3', 'IESS')], max_length=20)),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('centroCostos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.centrocostos')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.departamento')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='remuneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(choices=[('1', 2021), ('2', 2022)], max_length=4)),
                ('mes', models.CharField(choices=[('1', 'ENERO'), ('2', 'FEBRERO'), ('3', 'MARZO'), ('4', 'ABRIL'), ('5', 'MAYO'), ('6', 'JUNIO'), ('7', 'JULIO'), ('8', 'AGOSTO'), ('9', 'SEPTIEMBRE'), ('10', 'OCTUBRE'), ('11', 'NOVIEMBRE'), ('12', 'DICIEMBRE')], max_length=20)),
                ('dias', models.IntegerField(default=30, validators=[django.core.validators.MaxValueValidator(30)])),
                ('horas25', models.FloatField(default=0)),
                ('valor25', models.FloatField(default=0)),
                ('horas50', models.FloatField(default=0)),
                ('valor50', models.FloatField(default=0)),
                ('extraHoras100', models.FloatField(default=0)),
                ('valor100', models.FloatField(default=0)),
                ('comisiones', models.FloatField(default=0)),
                ('bonoAdicional', models.FloatField(default=0)),
                ('IESSpersonal', models.FloatField(default=0)),
                ('retencionIR', models.FloatField(default=0)),
                ('prestamoIESS', models.FloatField(default=0)),
                ('extConyuges', models.FloatField(default=0)),
                ('otrosDescuentos', models.FloatField(default=0)),
                ('multas', models.FloatField(default=0)),
                ('anticipos', models.FloatField(default=0)),
                ('otrosPrestamos', models.FloatField(default=0)),
                ('movilizacion', models.FloatField(default=0)),
                ('transporte', models.FloatField(default=0)),
                ('pagoXIII', models.FloatField(default=0)),
                ('pagoXIV', models.FloatField(default=0)),
                ('pagoFR', models.FloatField(default=0)),
                ('pagoVacaciones', models.FloatField(default=0)),
                ('valorXIII', models.FloatField(default=0)),
                ('valorXIV', models.FloatField(default=0)),
                ('vacaciones', models.FloatField(default=0)),
                ('fondoReserva', models.FloatField(default=0)),
                ('IESSpatr', models.FloatField(default=0)),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Remuneracion',
                'verbose_name_plural': 'Remuneraciones',
                'unique_together': {('ano', 'mes', 'identificacion')},
            },
        ),
    ]
