# Generated by Django 4.0.6 on 2022-07-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_remuneracion_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fechaInicio',
            field=models.DateField(),
        ),
    ]
