# Generated by Django 4.0.6 on 2022-07-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_alter_empleado_fechainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
    ]
