# Generated by Django 4.0.6 on 2022-08-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_alter_empleado_vigente'),
    ]

    operations = [
        migrations.AddField(
            model_name='remuneracion',
            name='pagoExtCony',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='remuneracion',
            name='pagoIESS',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='remuneracion',
            name='pagoprestIESS',
            field=models.FloatField(default=0),
        ),
    ]
