# Generated by Django 4.0.6 on 2022-08-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_alter_remuneracion_pagoextcony_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remuneracion',
            name='pagoExtCony',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='remuneracion',
            name='pagoIESS',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='remuneracion',
            name='pagoVacaciones',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='remuneracion',
            name='pagoprestIESS',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
