# Generated by Django 4.0.6 on 2022-08-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_alter_remuneracion_pagoextcony_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
