# Generated by Django 4.0.6 on 2022-08-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0009_empleado_direccion_empleado_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cargasFamiliares',
            field=models.IntegerField(default=0),
        ),
    ]
