# Generated by Django 4.0.6 on 2022-08-22 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0005_tipoitem_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='planCuentas',
            fields=[
                ('cuenta', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Cuenta')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('signo', models.CharField(choices=[('P', 'Positivo'), ('N', 'Negativo')], max_length=150, verbose_name='Signo')),
                ('tipoCuenta', models.CharField(choices=[('Acm', 'Acumulación'), ('EyE', 'Efectivo y Equivalentes'), ('CCcp', 'Cuenta por Cobrar CP'), ('Inv', 'Inventarios'), ('IA', 'Impuestos Activos'), ('IR', 'Impuestos Retenidos'), ('CClp', 'Cuenta por Cobrar LP'), ('PPyE', 'Propiedad, Plata y Equipo'), ('CPcp', 'Cuenta por Pagar CP'), ('CPlp', 'Cuenta por Pagar LP'), ('RIp', 'Retenciones IVA pasivo'), ('RRp', 'Retenciones Renta pasivo'), ('BEp', 'Beneficios Empleados x pagar'), ('BSp', 'Beneficios Sociales x pagar')], max_length=150, verbose_name='Tipo de Cuenta')),
                ('tipoEstado', models.CharField(choices=[('1', 'Estado Situacion Financiera'), ('2', 'Estado de Resultados Integrales'), ('3', 'Estado de Flujo de Efectivo'), ('5', 'Estado de Cambios en el Patrimonio')], max_length=150, verbose_name='Tipo Estado de Cuenta')),
                ('ctaAcumulacion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cuenta ACM')),
                ('activo', models.BooleanField(default=True, verbose_name='Estado')),
                ('nivel', models.CharField(choices=[('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3'), ('4', 'Nivel 4'), ('5', 'Nivel 5'), ('6', 'Nivel 6')], max_length=150, verbose_name='Nivel')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Plan de Cuentas',
            },
        ),
        migrations.CreateModel(
            name='compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEmision', models.DateField()),
                ('fechaContable', models.DateField()),
                ('tipoDcto', models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, to='config.documento')),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('inventario', models.BooleanField(default=False, verbose_name='Inventario')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('activo', models.BooleanField(default=True, verbose_name='Estado')),
                ('IVA', models.CharField(choices=[('No objeto IVA', 'No objeto IVA'), ('IVA 0%', 'IVA 0%'), ('IVA diferente 0%', 'IVA diferente 0%'), ('IVA Exento', 'IVA Exento')], default=True, max_length=20, verbose_name='IVA')),
                ('ctaCostos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctaCostos', to='transacciones.plancuentas', verbose_name='Cuenta Ctble Costos')),
                ('ctaGastos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctaGastos', to='transacciones.plancuentas', verbose_name='Cuenta Ctble Gastos')),
                ('ctaIngresos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctaIngresos', to='transacciones.plancuentas', verbose_name='Cuenta Ctble Ingresos')),
                ('ctaInventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctaInventario', to='transacciones.plancuentas', verbose_name='Cuenta Ctble Inventario')),
                ('tipoItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.tipoitem', verbose_name='Tipo de Item')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'unique_together': {('tipoItem', 'descripcion')},
            },
        ),
    ]
