# Generated by Django 4.0.6 on 2022-08-22 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='items',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='items',
            name='IVA',
            field=models.CharField(max_length=200, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='items',
            name='codigo',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='items',
            name='ctaCostos',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CuentaCostos', to='transacciones.plancuentas', verbose_name='Cuenta Costos'),
        ),
        migrations.AlterField(
            model_name='items',
            name='ctaGastos',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CuentaGastos', to='transacciones.plancuentas', verbose_name='Cuenta Gastos'),
        ),
        migrations.AlterField(
            model_name='items',
            name='ctaIngresos',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CuentaIngresos', to='transacciones.plancuentas', verbose_name='Cuenta Ingresos'),
        ),
        migrations.AlterField(
            model_name='items',
            name='ctaInventario',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CuentaInventario', to='transacciones.plancuentas', verbose_name='Cuenta Inventario'),
        ),
        migrations.AlterField(
            model_name='items',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='items',
            name='inventario',
            field=models.BooleanField(default=True, verbose_name='Inventario'),
        ),
        migrations.AlterField(
            model_name='items',
            name='tipoItem',
            field=models.CharField(max_length=10, verbose_name='Tipo de Item'),
        ),
        migrations.AlterField(
            model_name='plancuentas',
            name='ctaAcumulacion',
            field=models.CharField(default=1, max_length=20, verbose_name='Cuenta ACM'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plancuentas',
            name='cuenta',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Cuenta'),
        ),
        migrations.AlterField(
            model_name='plancuentas',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='plancuentas',
            name='nivel',
            field=models.CharField(choices=[('1', 'Nivel1'), ('2', 'Nivel2'), ('3', 'Nivel3'), ('4', 'Nivel4'), ('5', 'Nivel5'), ('6', 'Nivel6')], max_length=20, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='plancuentas',
            name='signo',
            field=models.CharField(choices=[('P', 'Positivo'), ('N', 'Negativo')], max_length=20, verbose_name='Signo'),
        ),
        migrations.AlterField(
            model_name='plancuentas',
            name='tipoCuenta',
            field=models.CharField(choices=[('EyE', 'Efectivo y Equivalentes')], max_length=20, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AlterField(
            model_name='plancuentas',
            name='tipoEstado',
            field=models.CharField(max_length=20, verbose_name='Tipo de Estado'),
        ),
        migrations.DeleteModel(
            name='compras',
        ),
    ]
