# Generated by Django 4.0.6 on 2022-08-22 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_tipoitem_activo'),
        ('transacciones', '0002_alter_items_unique_together_alter_items_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='tipoItem',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='config.tipoitem', verbose_name='Tipo de Item'),
        ),
    ]
