# Generated by Django 4.0.6 on 2022-08-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0004_alter_plancuentas_tipocuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancuentas',
            name='ctaAcumulacion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cuenta ACM'),
        ),
    ]
