# Generated by Django 4.0.6 on 2022-07-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='centrocostos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True, verbose_name='Centro de Costos')),
            ],
            options={
                'verbose_name': 'Centro de Costo',
                'verbose_name_plural': 'Centro de Costos',
            },
        ),
        migrations.CreateModel(
            name='compania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=13, unique=True, verbose_name='Identificacion')),
                ('razonSocial', models.CharField(max_length=100, verbose_name='Razon Social')),
                ('nombreComercial', models.CharField(max_length=100, verbose_name='Nombre Comercial')),
                ('tipoContribuyente', models.CharField(choices=[('1', 'Sector Publico'), ('2', 'Contribuyente Especial'), ('3', 'Regimen General'), ('4', 'Regimen RIMPE'), ('5', 'Negocio Popular RIMPE')], max_length=2, verbose_name='Tipo de Contribuyente')),
                ('llevaContabilidad', models.BooleanField(verbose_name='Lleva Contabilidad')),
                ('direccion', models.CharField(max_length=255, verbose_name='Direccion Compañia')),
            ],
        ),
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True, verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
    ]
