# Generated by Django 4.0.6 on 2022-08-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compania',
            name='establecimiento',
            field=models.CharField(default='0001', max_length=4, verbose_name='Establecimiento'),
        ),
    ]
