# Generated by Django 4.0.6 on 2022-08-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_compania_establecimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Documento')),
            ],
        ),
    ]
