# Generated by Django 4.0.6 on 2022-08-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
            ],
        ),
    ]
