# Generated by Django 4.0.6 on 2022-08-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_tipoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoitem',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
